---
engines:
  duplication:
    enabled: true
    exclude_fingerprints:
    - fe6983f2eaa6f000004449d2579c32ce
    - a8e5f920a15822b579517529bdcd35bb
    - 4c4b56fc277494fafed4603b2b3abfc0
    - 3d5bdb4d43985e98e57c59f863aa536
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  eslint:
    enabled: true
    exclude_fingerprints:
    - 52a6d397239e349eb126f30a952e04e9
  fixme:
    enabled: true
ratings:
  paths:
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
- config/
- tests/
- vendor/
